-- HommLink CRM Complete Database Setup
-- Bu dosyayı Supabase SQL Editor'da tek seferde çalıştırabilirsiniz

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users tablosu (basit yapı)
CREATE TABLE public.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_uid uuid UNIQUE,
  full_name text,
  role text DEFAULT 'agent',
  created_at timestamptz DEFAULT now()
);

-- Status definitions tablosu (dinamik durum yönetimi)
CREATE TABLE public.status_definitions (
  id serial PRIMARY KEY,
  code text UNIQUE,
  label text,
  color text,
  order_index int DEFAULT 0,
  is_active boolean DEFAULT true
);

-- Leads tablosu (ana aday yönetimi)
CREATE TABLE public.leads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id text,
  source text,
  name text,
  phone text,
  region text,
  city text,
  status_id int REFERENCES public.status_definitions(id),
  notes text,
  next_action text,
  next_action_at timestamptz,
  owner_uid uuid REFERENCES public.users(auth_uid),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Lead events tablosu (tüm etkileşim geçmişi)
CREATE TABLE public.lead_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id uuid REFERENCES public.leads(id) ON DELETE CASCADE,
  event_type text,
  disposition text,
  note text,
  created_by uuid REFERENCES public.users(auth_uid),
  created_at timestamptz DEFAULT now()
);

-- Updated_at trigger fonksiyonu
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger AS $$ 
BEGIN 
  NEW.updated_at = now(); 
  RETURN NEW; 
END; 
$$ LANGUAGE plpgsql;

-- Trigger
CREATE TRIGGER trg_leads_touch 
  BEFORE UPDATE ON public.leads
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- Indexes for performance
CREATE INDEX idx_leads_owner_uid ON public.leads(owner_uid);
CREATE INDEX idx_leads_status_id ON public.leads(status_id);
CREATE INDEX idx_leads_phone ON public.leads(phone);
CREATE INDEX idx_lead_events_lead_id ON public.lead_events(lead_id);
CREATE INDEX idx_users_auth_uid ON public.users(auth_uid);

-- Enable RLS on all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.status_definitions ENABLE ROW LEVEL SECURITY;

-- Users table policies
CREATE POLICY "Users can view own profile" ON public.users
  FOR SELECT USING (auth_uid = auth.uid());

CREATE POLICY "Users can update own profile" ON public.users
  FOR UPDATE USING (auth_uid = auth.uid());

CREATE POLICY "Admins can view all users" ON public.users
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE auth_uid = auth.uid() AND role = 'admin'
    )
  );

-- Leads table policies
CREATE POLICY "Agents can view own leads" ON public.leads
  FOR SELECT USING (owner_uid = auth.uid());

CREATE POLICY "Admins can view all leads" ON public.leads
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE auth_uid = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Users can create own leads" ON public.leads
  FOR INSERT WITH CHECK (owner_uid = auth.uid());

CREATE POLICY "Users can update own leads" ON public.leads
  FOR UPDATE USING (owner_uid = auth.uid());

CREATE POLICY "Users can delete own leads" ON public.leads
  FOR DELETE USING (owner_uid = auth.uid());

-- Lead events table policies
CREATE POLICY "Users can view own lead events" ON public.lead_events
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.leads 
      WHERE id = lead_events.lead_id AND owner_uid = auth.uid()
    )
  );

CREATE POLICY "Admins can view all lead events" ON public.lead_events
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE auth_uid = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Users can create own lead events" ON public.lead_events
  FOR INSERT WITH CHECK (
    created_by = auth.uid() AND
    EXISTS (
      SELECT 1 FROM public.leads 
      WHERE id = lead_events.lead_id AND owner_uid = auth.uid()
    )
  );

-- Status definitions policies
CREATE POLICY "Authenticated users can view status definitions" ON public.status_definitions
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can manage status definitions" ON public.status_definitions
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE auth_uid = auth.uid() AND role = 'admin'
    )
  );

-- WhatsApp templates tablosu
CREATE TABLE public.whatsapp_templates (
  id serial PRIMARY KEY,
  code text UNIQUE NOT NULL,
  name text NOT NULL,
  message text NOT NULL,
  variables text[] DEFAULT '{}',
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS on whatsapp_templates
ALTER TABLE public.whatsapp_templates ENABLE ROW LEVEL SECURITY;

-- WhatsApp templates policies (read-only for all authenticated users)
CREATE POLICY "Authenticated users can view templates" ON public.whatsapp_templates
  FOR SELECT USING (auth.role() = 'authenticated');

-- Only admins can modify templates
CREATE POLICY "Admins can manage templates" ON public.whatsapp_templates
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE auth_uid = auth.uid() AND role = 'admin'
    )
  );

-- Insert initial status definitions
INSERT INTO public.status_definitions (code, label, color, order_index) VALUES
  ('NEW', 'Yeni', '#D1FAE5', 10),
  ('TO_CALL', 'Aranacak', '#E0E7FF', 20),
  ('WA_SENT', 'Cevap Bekleniyor (WA)', '#FEF3C7', 40),
  ('APPT_SET', 'Randevu Verildi', '#FDE68A', 50),
  ('APPT_CONFIRMED', 'Randevu Onaylandı', '#FCD34D', 55),
  ('FOLLOW_UP', 'Takipte', '#DBEAFE', 60),
  ('QUALIFIED', 'Nitelikli', '#A7F3D0', 70),
  ('CLOSED', 'Kapanmış', '#E5E7EB', 90);

-- Insert demo user for testing
INSERT INTO public.users (id, auth_uid, full_name, role) VALUES
  ('00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000000', 'Demo User', 'agent')
ON CONFLICT (auth_uid) DO NOTHING;

-- Insert WhatsApp message templates
INSERT INTO public.whatsapp_templates (code, name, message, variables) VALUES
  ('ilkMesaj','İlk Tanışma 🌿','Merhaba {{ad}}! 🌿 Ben {{ajan}}, Homm Bitkisel''den yazıyorum. Sizi aramıştım ama ulaşamadım. Doğal ürünlerle hem sağlığınıza hem de cebinize katkı sağlayacak harika bir fırsat var! 💚 2-3 dakika konuşabilir miyiz?',ARRAY['ad', 'ajan']),
  ('cevapsizArama','Cevapsız Arama 📞','{{ad}}, merhaba! 😊 Az önce sizi aradım ama meşguldünüz galiba. Homm Bitkisel''le ilgili çok heyecan verici bir konuyu paylaşmak istiyorum! Müsait olduğunuzda beni arayabilir misiniz? 🌟',ARRAY['ad']),
  ('randevuOner','Randevu Teklifi 📅','{{ad}}, harika! 🎉 O zaman {{tarih}} günü saat {{saat}}''te konuşalım mı? Size Homm Bitkisel''in sunduğu muhteşem fırsatları anlatacağım! Hem doğal yaşam hem de ek gelir... 💰✨',ARRAY['ad', 'tarih', 'saat']),
  ('randevuOnay','Randevu Onayı ✅','Süper {{ad}}! 🙌 {{tarih}} {{saat}} randevumuz kesin! Sizi arayacağım ve hayatınızı değiştirecek bu fırsatı detaylıca anlatacağım. Heyecanlıyım! 🚀💚',ARRAY['ad', 'tarih', 'saat']),
  ('hatirlatma','Randevu Hatırlatması ⏰','{{ad}}, merhaba! 😊 Bugün saat {{saat}}''te görüşeceğimizi hatırlatmak istedim. Homm Bitkisel''le ilgili size anlatacaklarım var ki... Çok heyecanlıyım! 🌟 Hazır mısınız?',ARRAY['ad', 'saat']),
  ('takip','Takip Mesajı 🔄','Merhaba {{ad}}! 🌿 Geçen konuşmamızı düşünüyordum... Homm Bitkisel ailesine katılma konusunda ne düşünüyorsunuz? Bu fırsat çok değerli ve sizi kaçırmak istemiyorum! 💎 Konuşabilir miyiz?',ARRAY['ad']),
  ('motivasyon','Motivasyon Mesajı 💪','{{ad}}, bugün harika bir gün! 🌞 Homm Bitkisel''le hayallerinizi gerçekleştirme zamanı geldi! Doğal ürünlerle hem sağlık hem de finansal özgürlük... Başlamaya hazır mısınız? 🚀💚',ARRAY['ad']),
  ('basari','Başarı Hikayesi 🏆','{{ad}}, size müthiş bir haber! 🎉 Geçen ay ekibimizden {{isim}} {{miktar}} TL kazandı! Homm Bitkisel''le bu başarı sizin de olabilir. Nasıl mı? Hemen konuşalım! 💰✨',ARRAY['ad', 'isim', 'miktar']),
  ('kapanis','Kapanış Mesajı 🤝','{{ad}}, bilgi verdiğiniz için çok teşekkürler! 🙏 Şu an uygun değilseniz anlayışla karşılıyorum. Homm Bitkisel ailesi her zaman burada! İleride fikrini değiştirirseniz, kapımız açık! 💚🌿',ARRAY['ad']);